import { cookies } from 'next/headers'
import { NextResponse } from 'next/server'
import { createServerClient } from '@supabase/ssr'
import type { NextRequest } from 'next/server'

export async function GET(request: NextRequest) {
  const { searchParams, origin } = new URL(request.url)
  const code = searchParams.get('code')
  const next = searchParams.get('next') ?? '/dashboard'

  if (code) {
    const cookieStore = await cookies()
    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
          getAll() {
            return cookieStore.getAll()
          },
          setAll(cookiesToSet) {
            try {
              cookiesToSet.forEach(({ name, value, options }) =>
                cookieStore.set(name, value, options)
              )
            } catch {
              // The `setAll` method was called from a Server Component.
              // This can be ignored if you have middleware refreshing
              // user sessions.
            }
          },
        },
      }
    )
    const { error } = await supabase.auth.exchangeCodeForSession(code)
    if (!error) {
      // Check if this is a new user who needs to set up their username
      const { data: { user } } = await supabase.auth.getUser()
      
      if (user) {
        // Check if user has a profile
        const { data: profile } = await supabase
          .from('profiles')
          .select('username, created_at')
          .eq('id', user.id)
          .single()

        // Check if user needs username setup:
        // 1. No profile exists
        // 2. Profile exists but username is auto-generated (starts with "user" followed by random chars)
        // 3. User metadata doesn't have preferred_username (meaning they signed up via Google)
        const hasPreferredUsername = user.user_metadata?.preferred_username
        const isAutoGeneratedUsername = profile?.username && 
          profile.username.startsWith('user') && 
          profile.username.length > 10 &&
          /^user[a-z0-9]{6,}$/.test(profile.username)

        const needsUsernameSetup = !profile || 
          (profile && isAutoGeneratedUsername && !hasPreferredUsername) ||
          (profile && !hasPreferredUsername && !profile.username.match(/^[a-zA-Z0-9_-]{3,30}$/))

        if (needsUsernameSetup) {
          return NextResponse.redirect(`${origin}/auth/setup-username`)
        }
      }

      return NextResponse.redirect(`${origin}${next}`)
    }
  }

  // return the user to an error page with instructions
  return NextResponse.redirect(`${origin}/auth/auth-code-error`)
} 